name: Deploy Backend to Azure

on:
  push:
    branches: [ master ]
    paths:
      - 'backend/**'
      - '.github/workflows/deploy-azure.yml'
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore backend/PetClothingShop.sln

    - name: Build backend
      run: dotnet build backend/PetClothingShop.API/PetClothingShop.API.csproj -c Release --no-restore

    - name: Publish backend
      run: dotnet publish backend/PetClothingShop.API/PetClothingShop.API.csproj -c Release -o ./publish --no-build

    - name: Deploy to Azure App Service
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'pet-clothing-shop-api'
        publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
        package: ./publish

    - name: Health check
      run: |
        sleep 30
        curl -f https://pet-clothing-shop-api.azurewebsites.net/health || true
